### PR TITLE
fix: drop `declare module '@vue/runtime-core'`

### LINKED ISSUE #358: Using only `declare module 'vue'`
### Describe the feature

`vue-router` 在更新到 `4.4.1` 后移除了 `declare module '@vue/compiler-core'` 的定义 https://github.com/vuejs/router/commit/4f082cd ，这将导致 `unimport` 生成的类型声明产生中断从而造成一些类型错误，比如 vue 模板内由插件添加的 `globalProperties` 下的属性类型丢失  https://github.com/vuejs/router/discussions/2321 。

我并不清楚造成这种类型错误的根本原因，也缺乏向下兼容的经验，如果能得到解答将非常感激。

### Additional information

- [X] Would you be willing to help implement this feature?

### PR DESCRIPTION
**Pull request by KazariEX**
resolve #358

### CODE REVIEW

File: src/addons/vue-template.ts [hunk 1]
```diff
@@ -82,13 +82,6 @@ declare module 'vue' {
 ${extendItems}
   }
 }` // Workaround for Vue 3.3
```
Comment (antfu) [inline src/addons/vue-template.ts:84]:
```suggestion
}`
```

**Review by antfu — APPROVED** [review]

**Comment by davidstackio** [comment]
When I updated unimport from `3.9.1` to `3.10.0` it broke the auto imports for utils in my Nuxt `3.12.4` project. When I downgraded back to `3.9.1` it worked again. This might be a breaking change for some users.
