### PR TITLE
fix(dedupeImports): respect negative and zero import priorities

### LINKED ISSUE #524: warn: duplicate "useAppConfig" surfaced in Nuxt 4.4.2 / Nitro after unimport 6.1.0
### Environment

- Nuxt: `4.4.2`
- Nitro: `2.13.3`
- Node: `22.x`
- Package manager: `npm`
- OS: macOS

### Warning

After reinstalling dependencies, `nuxt typecheck` and dev startup started emitting:

```txt
WARN  Duplicated imports "useAppConfig", the one from "nitropack/runtime/internal/config" has been ignored and ".../@nuxt/nitro-server/dist/runtime/utils/app-config" is used
```

The app still runs, but the warning is repeated.

### What changed

In our repo, the app-level Nuxt version did **not** change.

Relevant lockfile delta:

- `nuxt` -> `4.4.2`
- `@nuxt/nitro-server` -> `4.4.2`
- `nitropack` -> `2.13.3`
- nested `unimport` changed `6.0.2 -> 6.1.0` under both `nuxt` and `nitropack`

### Generated output showing the duplicate sources

Nuxt generates these entries:

```ts
// .nuxt/types/nitro-imports.d.ts
const useAppConfig: typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/utils/app-config').useAppConfig
const useRuntimeConfig: typeof import('../../node_modules/nitropack/dist/runtime/internal/config').useRuntimeConfig

export { useRuntimeConfig } from 'nitropack/runtime/internal/config'
export { useAppConfig } from '.../node_modules/@nuxt/nitro-server/dist/runtime/utils/app-config'
```

At the same time, Nitro also exports `useAppConfig` from `nitropack/runtime/internal/config`.

So the underlying duplicate source pair seems to exist in the Nuxt/Nitro integration, but `unimport` is the layer that emits the warning.

### Why I'm filing here

`unimport@6.1.0` includes a rewrite of `dedupeImports` in:

- https://github.com/unjs/unimport/pull/507

That change looks like the most likely reason this duplicate is now being surfaced as a warning in setups that previously stayed quiet.

I'm not certain whether the root bug is:
1. a Nuxt/Nitro duplicate that `unimport` now reports more aggressively, or
2. a regression in `unimport` deduplication/warning behavior itself.

But the first visible change on our side was the nested `unimport` bump to `6.1.0`, while `nuxt@4.4.2` stayed fixed.

### Reproduction notes

I can reproduce with:

```bash
npm install
npx nuxt typecheck
```

and also during dev startup.

### PR DESCRIPTION
**Pull request by 8ctavio**
Resolves #524.

The current implementation of `dedupeImports` ignores negative priorities in some cases. This PR implements proper support for imports' negative priorities.

In the linked issue, there's a warning for Nuxt's `useAppConfig` import, which [uses a negative priority of `-1`](https://github.com/nuxt/nuxt/blob/v4.2.2/packages/nitro-server/src/index.ts#L324), so I think not properly handling negative priorities is causing that issue.

## Summary by CodeRabbit

* **Bug Fixes**
  * Refined duplicate-import resolution so negative and zero priorities are handled correctly; default-priority imports are no longer erroneously replaced by lower-priority duplicates.

* **Tests**
  * Added tests to verify behavior for negative and zero priority duplicates and ensure no spurious warnings are emitted.

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -168,7 +168,10 @@ export function dedupeImports(imports: Import[], warn: (msg: string) => void) {
     // currImp and prevImp are duplicate imports
     const altName = encodeImportName(name)
     const prevImpComplement = deduped.get(altName)
-    const priorityDiff = (currImp.priority || 1) - Math.max(prevImp.priority || 1, prevImpComplement?.priority || 1)
+    const prevPriority = prevImpComplement
+      ? Math.max(prevImp.priority || 1, prevImpComplement.priority || 1)
```
Comment (danielroe) [inline src/utils.ts:172]: we should use `??` rather than `||` to respect priority of `0`

Comment (8ctavio) [reply src/utils.ts:172]: Should we do that now? I kept `||` for compatibility, but I can change to `??` if that's not an issue.
